### ISSUE TITLE
User can modify other user question

### ISSUE THREAD

**Issue by aritra7** [tecnickcom/tcexam#261] opened 2019-08-20 17:13 UTC
When I created different users for my institute, then I face an issue, that is every user can edit, delete and modify each other question. Please tell me a solution that can help me to separate the user. No user can access other user's questions. Please tell me the way.

**Comment by nicolaasuni** [comment] 2019-08-20 18:11
I am unable to reproduce your issue.
Are you using the latest TCExam?
Has each user an individual account?

**Comment by aritra7** [comment] 2019-08-20 18:17
Yes, I'm using the latest version.
I've created 5 accounts of test takers. Each level is 5. I'm finding a way in that no test taker can access another test taker's questions. Is there any way?

**Comment by nicolaasuni** [comment] 2019-08-20 18:22
Test takers should have level 1.

**Comment by aritra7** [comment] 2019-08-20 18:29
But the test taker means the teachers above Level 4 can't create any questions. Can I restrict the user? I want a way that no user can access another user question. From level 1-4 no one can create questions. After level 5 they can create questions. But the problem is one user can access another user's questions. Is there any way to restrict them?

**Comment by nicolaasuni** [comment] 2019-08-20 18:44
Each module is assigned to an author.
The users that can edit a module (and relative questions) are:
* the administrators;
* the original author;
* people in the same group as the author.

So, in your case I guess you should put users in different groups.

**Comment by aritra7** [comment] 2019-08-20 19:14
Thanks, problem solved.

**Closed** 2019-08-20 19:15 UTC
