### ISSUE TITLE
Error: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php

### ISSUE THREAD

**Issue by rekja** [tecnickcom/tcexam#237] opened 2018-12-11 23:47 UTC
Hello

I have such a problem when displaying test results. Configuration: PHP7 and TCExam ver. 14.1.9.
the error only occurs for the option
statistic: disable
graph: unchecked

`ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 60 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 65 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php
ERROR: [2] A non-numeric value encountered | LINE: 79 | FILE: /srv/http/TCExam_16/shared/code/tce_functions_statistics.php`

Greetings
Jarek

**Comment by damms005** [comment] 2019-01-18 14:33
It is not straightforward to resolve your issue without some more information about your server env. Also, the error line references that you posted suggests that you may be running an old TCExam installation.
For a start at resolving this, I suggest that you should update your TCExam installation so that you are sure to be running the most current version.

**Comment by rekja** [comment] 2019-01-20 17:16
I have the latest version of TCExam installed.

The error indicates the following lines.
` $stats['sum'][$set] += $value;
$stats['range'][$set] = $stats['maximum'][$set] - $stats['minimum'][$set];
 $dev += pow(($value - $stats['mean'][$set]), 2);`

and applies: A non-numeric value encountered

**Comment by damms005** [comment] 2019-01-21 08:42
Incidentally, I cannot reproduce that. But I do not think it is a serious issue. However, for the mean time as a palliative measure, since it is only the `F_getArrayStatistics` function that resides inside the culprit file, you can simply put `error_reporting(0)` immediately inside the function body.

**Comment by IdenticalParticle** [comment] 2019-04-09 08:21
I also have to choose any other options except 'disabled' to avoid same error.
php fpm 7.3 and TCExam 14.1.9

**Comment by nicolaasuni** [comment] 2019-04-09 12:38
I have merged a fix on the development branch.
I will merge into master after some additional testing.

**Comment by nicolaasuni** [comment] 2019-11-07 07:36
I assume that the fix is working.

**Closed by nicolaasuni** 2019-11-07 07:36 UTC
