### ISSUE TITLE
Error when generating a PDF 

### ISSUE THREAD

**Issue by shakermohamed** [tecnickcom/tcexam#184] opened 2017-08-03 00:11 UTC
i am a new user and i need your help please, after install tcexam and write questions (about 10) i opened questions list and i want to make a PDF for all questions, then i got that error
ERROR: [2] getimagesize(/tcexam/cache/2.png): failed to open stream: No such file or directory | LINE: 6850 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/2.png): failed to open stream: No such file or directory | LINE: 1919 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\include\tcpdf_static.php
ERROR: [2] getimagesize(/tcexam/cache/Q10.PNG): failed to open stream: No such file or directory | LINE: 6850 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/Q10.PNG): failed to open stream: No such file or directory | LINE: 1919 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\include\tcpdf_static.php
ERROR: [2] getimagesize(/tcexam/cache/Q4.PNG): failed to open stream: No such file or directory | LINE: 6850 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/Q4.PNG): failed to open stream: No such file or directory | LINE: 1919 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\include\tcpdf_static.php
ERROR: [2] getimagesize(/tcexam/cache/Q6.PNG): failed to open stream: No such file or directory | LINE: 6850 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/Q6.PNG): failed to open stream: No such file or directory | LINE: 1919 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\include\tcpdf_static.php
ERROR: [2] getimagesize(/tcexam/cache/Q8.PNG): failed to open stream: No such file or directory | LINE: 6850 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/Q8.PNG): failed to open stream: No such file or directory | LINE: 1919 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\include\tcpdf_static.php
ERROR: [2] getimagesize(/tcexam/cache/Q9.PNG): failed to open stream: No such file or directory | LINE: 6850 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\tcpdf.php
ERROR: [2] file_get_contents(/tcexam/cache/Q9.PNG): failed to open stream: No such file or directory | LINE: 1919 | FILE: C:\xampp\htdocs\tcexam\shared\tcpdf\include\tcpdf_static.php
TCPDF ERROR: Some data has already been output, can't send PDF file
note : i take a screenshots for the questions

**Comment by nicolaasuni** [comment] 2017-08-30 17:47
closing as duplicate of https://github.com/tecnickcom/tcexam/issues/183

**Closed by nicolaasuni** 2017-08-30 17:47 UTC
