### ISSUE TITLE
Error when sending the results

### ISSUE THREAD

**Issue by haibaadel** [tecnickcom/tcexam#154] opened 2016-07-17 09:46 UTC
Hello Nicola, First of all I would like to thank you for this wonderful project, it's really useful peace of software.

I'm faced with one issue, and that is when I try to send the results by email I get this error message : -
{
Notice: Undefined property: C_mailer::$error_count in C:\xampp\htdocs\shared\code\tce_class_mailer.php on line 65

ERROR: [SMTP] Could not authenticate.
}

I'm really in a hurry fixing this problem.

I'll be waiting for your quick reply Nicola

Best regards

Adel Haiba

**Comment by nicolaasuni** [comment] 2016-08-21 19:22
Closing as this is a duplicate of:
https://github.com/tecnickcom/tcexam/issues/149
I will fix this soon.

**Closed by nicolaasuni** 2016-08-21 19:22 UTC
